repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff lint
      entry: poetry run ruff check
      language: system
      types_or: [python, pyi]
      args: [--fix, --force-exclude]

    - id: ruff-format
      name: ruff format
      entry: poetry run ruff format
      language: system
      types_or: [python, pyi]


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1  # Use the sha / tag you want to point at
  hooks:
  - id: mypy

