name: docker_compose_test
services:
    simplemath:
        # stdin_open: true
        # tty: true
        command: sleep infinity
        container_name: mymath
        ports:
            - 8888:8888
        image: smi
        build: 
          dockerfile: ./Dockerfile
          context: .
        volumes:
            - type: bind
              source: ./
              target: /usr/src/python_pkg