site_name: Simple Math Functions
site_url: https://goyalpike.github.io/github_actions/

# Repository
repo_name: goyalpike/github_actions/
repo_url: https://github.com/goyalpike/github_actions/
edit_uri: ""

theme:
  name: material
  font:
    text: Philosopher  # Change to any google font https://fonts.google.com/
  palette:
    # Palette toggle for light mode (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - content.tabs.link
    - search.suggest
    - search.highlight

copyright: Copyright &copy; 2024 Pawan Goyal

markdown_extensions:
  - admonition  # Used to enable additional markdown features such note, warning, error
  - pymdownx.highlight  # Used to do syntex highlight for code
  - pymdownx.superfences

plugins:
  - search
  - social
  - mkdocs-jupyter:
      execute: False
  - autorefs
  - mkdocs-autoapi
  - mkdocstrings:
      handlers:
        options:
          show_submodules: true
          show_source: true

nav:
  - Home: index.md
  - Examples: examples/*
  - API Documentation: code_documentation.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://goyalpike.github.io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/goyalpawank/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/pkgpawan
