site_name: Simple Math Functions
theme:
  name: material

markdown_extensions:
  - admonition

plugins:
  - search
  - mkdocs-jupyter
  - autorefs
  - mkdocs-autoapi
  - mkdocstrings:
      handlers:
        options:
          show_submodules: true
          show_source: true

nav:
  - Home: index.md
  - Examples: examples/*
  - Code Documentation: code_documentation.md