name: Create a comment on a new issue

on:
    issues: 
        types: [opened]

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: "dump github context"
              run: echo '${{ toJSON(github.event)}}' | jq
              shell: bash
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v1
              with:
                issue-number: ${{ github.event.issue.number }}
                body: |
                  This is a multi-line test comment
                  - With GitHub **Markdown** :sparkles:
                  - Created by [create-or-update-comment][1]
      
                  [1]: https://github.com/peter-evans/create-or-update-comment
                reactions: '+1'

    comments-with-api:
        runs-on: ubuntu-latest
        steps:
          - name: Create comment using GitHub API
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                REPO: ${{ github.repository }}
            run: |
                curl -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments \
                -d '{"body": "This is a multi-line test comment\n- With GitHub **Markdown** :sparkles:\n- Created by GitHub API"}'
            shell: bash

